<a href="https://colab.research.google.com/github/Likithanimmaganti/TEAM-12-PARKING-SYSTEM-/blob/main/IDS_LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import time

arr_basic = np.array([1, 2, 3, 4, 5])
print("Basic ndarray:", arr_basic)



Basic ndarray: [1 2 3 4 5]


In [6]:
import numpy as np
import time
arr_zeros = np.zeros((3, 3))
print("\nArray of zeros:\n", arr_zeros)




Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np
import  time
arr_ones = np.ones((2, 4))
print("\nArray of ones:\n", arr_ones)






Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
import numpy as np
import time

arr_random = np.random.rand(3, 2)
print("\nArray of random numbers:\n", arr_random)



Array of random numbers:
 [[0.47839168 0.68509489]
 [0.24153133 0.76488749]
 [0.29530393 0.81889777]]


In [8]:
import numpy as np
import time

arr_choice = np.array([10, 20, 30, 40])
print("\nArray of your choice:", arr_choice)




Array of your choice: [10 20 30 40]


In [9]:
import numpy as np
import time

arr_identity = np.eye(4)
print("\nIdentity matrix (Imatrix):\n", arr_identity)



Identity matrix (Imatrix):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
import numpy as np
import time
arr_evenly_spaced = np.linspace(0, 10, 5)
print("\nEvenly spaced ndarray:", arr_evenly_spaced)




Evenly spaced ndarray: [ 0.   2.5  5.   7.5 10. ]
